sudo: required
language: ruby
rvm:
  - "2.3.8"
  - "2.4.9"
  - "2.5.8"
  - "2.6.6"
  - "2.7.2"
gemfile:
  - gemfiles/Gemfile.rails-5.0.x
install:
  - "sudo pip install --upgrade pip"
  - "sudo pip install awsebcli --ignore-installed"
  - "gem install bundler"
  - "bundle install"

script:
   - "export EXCEPT_DEPLOYED=true"
   - "if [[ $TRAVIS_RUBY_VERSION == '2.4.2' ]]; then export EXCEPT_DEPLOYED=false; fi"
   - "bundle exec rspec spec"

matrix:
  exclude:
    # - rvm: "2.0"
    #   gemfile: gemfiles/Gemfile.rails-5.0.x
    # - rvm: "2.1"
    #   gemfile: gemfiles/Gemfile.rails-5.0.x
